In [1]:
import matplotlib.pyplot as plt
import numpy as np
list2=[[1,2],[3,4],[5,6]]
print(list2)

[[1, 2], [3, 4], [5, 6]]


In [2]:
twoArray=np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
four=np.array([[1,2,3],[4,5,6]])
print(four)

[[1 2 3]
 [4 5 6]]


In [4]:
four.shape=(3,2)
print(four)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
five=four.reshape(3,2)
print(five)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
five=five.reshape((6,),order='F')
six=five.flatten(order='F')
print(five)
print(six)

[1 3 5 2 4 6]
[1 3 5 2 4 6]


In [7]:
t1=np.arange(24).reshape((6,4))
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [8]:
import numpy as np
import matplotlib
us_file_path="./youtube_video_data/US_video_data_numbers.csv"
uk_file_path="./youtube_video_data/GB_video_data_numbers.csv"
t_us=np.loadtxt(us_file_path,delimiter=',',dtype="int")
t_us_comments=t_us[:,-1]
print(t_us_comments.max(),t_us_comments.min())
d=1000
bin_nums=(t_us_comments.max()-t_us_comments.min())
plt.figure(figsize=(20,8),dpi=80)
plt.hist(t_us_comments,bins=bin_nums)
plt.show()


FileNotFoundError: ./youtube_video_data/US_video_data_numbers.csv not found.